name: Build Debug APK

on:
  workflow_dispatch:  # 允许手动一键触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Log Gradle version
        run: ./gradlew --version  # 添加日志：输出Gradle版本以验证环境

      - name: Build debug APK
        run: ./gradlew assembleDebug  # 构建debug APK

      - name: Log APK path
        run: find app/build/outputs/apk -name '*.apk'  # 添加日志：输出APK路径以验证构建输出

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk  # 假设主模块为app，调整如果需要
