name: Debug Build

on:
  workflow_dispatch:  # 允许手动触发
  push:               # 也可以在推送时自动触发
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Prepare build files
        run: |
          # 创建空的google-services.json文件
          echo '{
            "project_info": {
              "project_number": "000000000000",
              "project_id": "dummy-project",
              "storage_bucket": "dummy-bucket.appspot.com"
            },
            "client": [{
              "client_info": {
                "mobilesdk_app_id": "1:000000000000:android:0000000000000000",
                "android_client_info": {
                  "package_name": "me.rerere.rikkahub"
                }
              },
              "api_key": [{
                "current_key": "dummy_key"
              }]
            }]
          }' > app/google-services.json

      - name: Gradle Build
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
